from flask import Flask

# Create a Flask application
app = Flask(__name__)

# Define a route for the homepage
@app.route('/')
def hello_world():
    return 'Hello, World!'
# Define a route for the health check
@app.route('/health')
def return_ok():
    return 'Ok', 200

# Run the Flask application
if __name__ == '__main__':
    app.config['FLASK_ENV'] = 'development'
    app.run(host ='0.0.0.0', port = '5000', debug ='1')
