apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-flask-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-flask
  minReplicas: 1
  maxReplicas: 5
  metrics:     
    - type: Resource       
      resource:         
        name: cpu         
        target:           
          type: Utilization
          averageUtilization: 50
