name: CI-pipeline 
on:
  push:
    branches:
      - 'main'
    paths:
      - "app.yaml"
      - "manifests/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: '${{ github.ref_name }}'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
