name: CI-pipeline 
on:
  push:
    branches:
      - 'main'
    paths:
      - "app.yaml"
      - "manifests/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: '${{ github.ref_name }}'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image from Dockerfile
      run: |
        docker build -t waeldalaous/app:v${{ github.run_id }}

    - name: Push Image to ECR REGISTRY
      run: |
        docker push waeldalaous/app:v${{ github.run_id }}

    - name: Set up YQ command
      run: |
        sudo snap install yq --channel=v3/stable

    - name: Edit manifests with new image
      run: |
          yq w -i ./manifests/deployment.yaml spec.template.spec.container[0].image 'waeldalaous/app:v${{ github.run_id }}'
    

    
